### ISSUE TITLE
Incorrect ffmpeg command line generation

### ISSUE THREAD

**Issue by gromgit** [0x776b7364/toggle.sg-download#13]
Running the latest script (commit 227b5f) on Linux with Python 2.7.10, in which `ffmpeg` fails on every download with `Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument`.

A little investigation revealed that the generated ffmpeg command line for, say, `http://video.toggle.sg/en/series/body-and-soul-s3/ep7/367036` looks like this:

`ffmpeg -i http://mcshls2015-vh.akamaihd.net/i/201601WM/MCPK0160202001100895/20160202_BODY_AND_SOUL_S3_EP7_STB_MP4_,10,30,.mp4.csmil/master.m3u8 -c copy -bsf:a aac_adtstoasc "http://mcshls2015-vh.akamaihd.net/i/201601WM/MCPK0160202001100895/20160202_BODY_AND_SOUL_S3_EP7_STB_MP4_,10,30,.mp4.csmil/master.m3u8.mp4"`

i.e. ffmpeg is being told to send the converted output right back to the hosting servers!

**Comment by 0x776b7364** [comment]
Confirmed. Meanwhile, the deprecated version should still work for m3u8 files.

**Comment by 0x776b7364** [comment]
I've uploaded a bugfix. Let me know if it still doesn't work.
cc @cmemil

**Comment by cmemil** [comment]
Tested it with [http://tv.toggle.sg/en/shows/splash-to-victory/episodes](url)
and can confirm that it works! Thank you so much.

**Comment by 0x776b7364** [comment]
Closed via d143a72.
