### ISSUE TITLE
Unable to download Telemovies

### ISSUE THREAD

**Issue by cmemil** [0x776b7364/toggle.sg-download#14]
I've tried multiple links and the script hangs on:

`[i] Obtaining URL records from download URL response ...`

Happens to the following Mediacorp telemovies:

[http://video.toggle.sg/en/movies/a-chance-of-life/305307](url)
[http://video.toggle.sg/en/movies/the-rangers/303714](url)
[http://video.toggle.sg/en/movies/deep-in-the-night/304795](url)
[http://video.toggle.sg/en/movies/hidden-scars/304320](url)

**Comment by 0x776b7364** [comment]
I'll work on it when I have more time. You're more than welcome to contribute by submitting pull requests. :)

**Comment by cmemil** [comment]
No worries. Take your time and thank you very much for this versatile script. :+1:

**Comment by 0x776b7364** [comment]
I'm getting errors playing the videos listed, probably due to geo-blocking (I'm overseas right now). Can't do much now, I'm afraid.

**Comment by cmemil** [comment]
That's fine. I'm sure we can all wait until you arrive home ;-)

**Comment by 0x776b7364** [comment]
Looks like this is related to #30. Do re-open this issue if it's not the case.
