### ISSUE TITLE
'ffmpeg file not found, or existing file is for incorrect architecture'.

### ISSUE THREAD

**Issue by saintlylindsey** [0x776b7364/toggle.sg-download#17]
tried to download http://video.toggle.sg/en/series/the-dream-makers-s2-2/ep1/346548 on Microsoft. the srt for the caption appears in my scripts folder, but I cant download the video. i get the following error prompt; 'ffmpeg file not found, or existing file is for incorrect architecture'.

**Comment by 0x776b7364** [comment]
Well, is the ffmpeg binary file present in the same folder as the script? Are you using the binary with the correct architecture (x86/x64)? Also, try disabling auto-download and selecting the mp4 version instead of the m3u8 version.

**Comment by saintlylindsey** [comment]
it works now! just wondering how long it would take to download, say, a 1hr video? mine has taken a few hours

**Comment by saintlylindsey** [comment]
also is it possible to pause the download and come back to it?

**Comment by 0x776b7364** [comment]
Download time depends on your Internet bandwidth - it's hard to say, but the download time should be less than the media runtime. I don't think you can pause the download; it you'd like, you can obtain the direct download URL by enabling debug mode, then using your download manager to queue the URLs. Glad it works for you. Closed.
