### ISSUE TITLE
ffmpeg is not recognize internal/external command, subtitles permission denied

### ISSUE THREAD

**Issue by BankofSwax** [0x776b7364/toggle.sg-download#18]
Hey I was try to download some show on toggle using your script, but no matter how I try, I always get the same error, and the script hang. Anything I do it wrongly?

**Comment by peterhoeg** [comment]
You probably want to look at this:
https://github.com/0x776b7364/toggle.sg-download#ffmpeg-dependency-notes

**Comment by BankofSwax** [comment]
[http://imgur.com/nO2aB4s](url)

I get this instead. Where will the download file go btw?

**Comment by 0x776b7364** [comment]
1) Do you already have ffmpeg downloaded and accessible through the global $PATH, or, present in the same folder as the script?
2) Do provide the Toggle URL so that I can try to replicate the issue.
3) The download file usually goes into the same directory as the script.

**Comment by BankofSwax** [comment]
[http://i.imgur.com/r2B55f3.jpg](url)

I insert the ffmpeg like this, is it correct? 

http://video.toggle.sg/en/series/118-hd/ep255/345142

**Comment by 0x776b7364** [comment]
Yes. Are you still having issues with the script and your URL? It works fine for me.

**Comment by peterhoeg** [comment]
FWIW, that video is downloading just fine for me as well (tried on both Arch Linux and NixOS).

**Comment by BankofSwax** [comment]
yup still same, how you guys do it may I know. Im using window

**Comment by 0x776b7364** [comment]
Do a full screen capture, with multiple screenshots if necessary, of the commands:
```
c:\your\path\here> dir
c:\your\path\here> download_toggle_video2.py http://video.toggle.sg/en/series/118-hd/ep255/345142
```

I'm assuming your IP address is a SG one.

**Comment by 0x776b7364** [comment]
Closed due to no-reply. Please re-open the issue if you're still facing problems.
