### ISSUE TITLE
more sites supported

### ISSUE THREAD

**Issue by Jai-GAY** [0x776b7364/toggle.sg-download#19]
I was wondering is there potential to support more sites ?
[more supported site ?](http://www.channel8news.sg/news8/ca/worldthisweek)

C:\xx\toggle.sg-download-master>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

C:\xx\toggle.sg-download-master>download_toggle_video2.py http://www.channel8news.sg/news8/ca/worldthisweek/20160321-wtw-seg1/2622450.html

=====================================
Toggle video and episodes downloader
by 0x776b7364
=====================================

================================
[*] Processing input 1 of 1 ...
================================
[!] Error: http://www.channel8news.sg/news8/ca/worldthisweek/20160321-wtw-seg1/2622450.html is not a valid URL
[!] Nothing to download for http://www.channel8news.sg/news8/ca/worldthisweek/20160321-wtw-seg1/2622450.html

[i] Starting download of queued URLs ...

[i] Done!
C:\xx\toggle.sg-download-master>

**Comment by 0x776b7364** [comment]
It's very unlikely that this script will support other sites. 
1. It's on a different domain.
2. The web player is ooyala (I believe), and not the same as Toggle's.
3. You're more than welcome to fork my code as a base for www.channel8news.sg. :)
