### ISSUE TITLE
File not saved after downloading and encoding

### ISSUE THREAD

**Issue by DavidLTX** [0x776b7364/toggle.sg-download#20]
Thanks for this python script. I've just downloaded it a few days ago. Finally managed to get all the files in the right places. However it doesn't seems to save the .mp4 after it was done with download and and encoding.

I've attached a screenshot of the cmd.

![capture](https://cloud.githubusercontent.com/assets/11645296/14280386/b94037c6-fb5c-11e5-98cf-74d88f793ea1.JPG)

How should I save the file after the ffmpeg is done with the encoding ?

Thanks for the help.

**Comment by gromgit** [comment]
I use Linux myself, but unless there's something unique about the way Python in Windows handles files, the resulting video should be in the directory from which you ran the script (i.e. `C:\` in the above screenshot).

**Comment by DavidLTX** [comment]
Hi Gromgit, thanks for your reply. I've tried it again.

![capture](https://cloud.githubusercontent.com/assets/11645296/14287604/80b53890-fb7d-11e5-80d3-c6dfaa016df2.JPG)

It's not in the `C:\` or the `C:\Python27`

I've also added the initial commands just in case I type in something wrong there.

![capture2](https://cloud.githubusercontent.com/assets/11645296/14287611/8867d0f2-fb7d-11e5-8157-8d2e826ec48d.JPG)

**Comment by peterhoeg** [comment]
Do users normally have access to write to the root of the C-drive? Try running it from somewhere else like "My Documents" or the Desktop.

**Comment by 0x776b7364** [comment]
I've just tried the script against the link http://video.toggle.sg/en/series/sealed-with-a-kiss-tif/webisodes/bloopers-1/342292. Both IPH and STB versions get correctly downloaded and stored on disk. Perhaps check your file permissions? Also, try navigating to the Python27 folder, then running the script, as such:

```
C:\Python27>download_toggle_video2.py http://video.toggle.sg/en/series/sealed-with-a-kiss-tif/webisodes/bloopers-1/342292
```

I did not consider local/relative file paths; I guess I could include that in future.

**Comment by anurupborah2001** [comment]
Thanks for the python Script .I have tried to download from toggle but i am unsuccessful to do it.
I have run the script as below : 
(download_toggle_video2.py http://video.toggle.sg/en/tv-show/news/mar-2016-cna-singapore-tonight/thu-31-mar-2016/388313)

![pythonissue](https://cloud.githubusercontent.com/assets/861835/14730094/206b5838-0876-11e6-9587-a2297048aa62.PNG)

Please kindly suggest what shall I do on my end.

**Comment by 0x776b7364** [comment]
That's easy - use Python 2.7. :) Python 3 is not supported yet.

**Comment by anurupborah2001** [comment]
Thanks a lot ..its working now

**Comment by 0x776b7364** [comment]
Issue closed due to inactivity. Please re-open this issue if you're still having problems.
