### ISSUE TITLE
Error: ffmpeg file not found 

### ISSUE THREAD

**Issue by noiseloops** [0x776b7364/toggle.sg-download#21]
just came across this script and it works swimmingly well. 

came across this issue however when it comes to this particular series/episodes:
http://video.toggle.sg/en/series/detik-2015-16-edisi-khas/ep5/385208

> C:\Python27\toggledl>download_toggle_video2.py http://video.toggle.sg/en/series/
> detik-2015-16-edisi-khas/ep5/385208
> 
> =====================================
> Toggle video and episodes downloader
> by 0x776b7364
> =====================================
> 
> ================================
> [*] Processing input 1 of 1 ...
> ================================
> 
> [i] Toggle video http://video.toggle.sg/en/series/detik-2015-16-edisi-khas/ep5/3
> 85208 detected
> [i] Obtained mediaID = 385208
> [i] Performing HTTP GET request on Toggle video URL ...
> [i] Obtained apiUser = tvpapi_147
> [i] Obtained apiPass = 11111
> [i] Performing HTTP GET request on download URL ...
> [i] Performing JSON parsing ...
> 
> [i] Obtaining media name ...
> [i] Obtained media name = Detik_2015/16_Edisi_Khas_-_Episode_5
> [i] Obtaining URL records from download URL response ...
> 
> 
> [i] Auto-selected URL: http://mcshls2015-vh.akamaihd.net/i/201601WM/MCPK01603230
> 01100913/20160323_DETIK_2015_EDISI_KHAS_EP5_STB_MP4_,10,30,.mp4.csmil/master.m3u
> 8
> [i] Performing HTTP GET request to check for subtitles ...
> [i] Performing JSON parsing ...
> [!] No subtitles found!
> 
> [i] Starting download of queued URLs ...
> 
> [i] Thread a0d75f50: processing URL http://mcshls2015-vh.akamaihd.net/i/201601WM
> /MCPK0160323001100913/20160323_DETIK_2015_EDISI_KHAS_EP5_STB_MP4_,10,30,.mp4.csm
> il/master.m3u8
> 
> [i] Crafting ffmpeg command ...
> [i] Executing ffmpeg command ...
> 
> ffmpeg version N-71497-gedbb9b5 Copyright (c) 2000-2015 the FFmpeg developers
>   built with gcc 4.9.2 (GCC)
>   configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-av
> isynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enab
> le-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --
> enable-libdcadec --enable-libfreetype --enable-libgme --enable-libgsm --enable-l
> ibilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enab
> le-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --en
> able-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --ena
> ble-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc
>  --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enabl
> e-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-lzma --ena
> ble-decklink --enable-zlib
>   libavutil      54. 22.101 / 54. 22.101
>   libavcodec     56. 34.100 / 56. 34.100
>   libavformat    56. 30.100 / 56. 30.100
>   libavdevice    56.  4.100 / 56.  4.100
>   libavfilter     5. 14.100 /  5. 14.100
>   libswscale      3.  1.101 /  3.  1.101
>   libswresample   1.  1.100 /  1.  1.100
>   libpostproc    53.  3.100 / 53.  3.100
> [h264 @ 0000000002e16520] non-existing SPS 0 referenced in buffering period
>     Last message repeated 1 times
> [h264 @ 0000000005fde4e0] non-existing SPS 0 referenced in buffering period
>     Last message repeated 1 times
> [h264 @ 0000000002dd7920] non-existing SPS 0 referenced in buffering period
> [h264 @ 0000000005fce980] non-existing SPS 0 referenced in buffering period
> Input #0, hls,applehttp, from 'http://mcshls2015-vh.akamaihd.net/i/201601WM/MCPK
> 0160323001100913/20160323_DETIK_2015_EDISI_KHAS_EP5_STB_MP4_,10,30,.mp4.csmil/ma
> ster.m3u8':
>   Duration: 00:24:22.55, start: 0.100667, bitrate: 0 kb/s
>   Program 0
>     Metadata:
>       variant_bitrate : 809000
>     Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709)
> , 1024x576 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
>     Metadata:
>       variant_bitrate : 809000
>     Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, flt
> p, 92 kb/s
>     Metadata:
>       variant_bitrate : 809000
>   Program 1
>     Metadata:
>       variant_bitrate : 1612000
>     Stream #0:2: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709)
> , 1024x576 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
>     Metadata:
>       variant_bitrate : 1612000
>     Stream #0:3: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, flt
> p, 92 kb/s
>     Metadata:
>       variant_bitrate : 1612000
> Detik_2015/16_Edisi_Khas_-_Episode_5_STB.mp4: No such file or directory
> 
> [!] Error: ffmpeg file not found, or existing file is for incorrect architecture
> .
> [i] Thread a0d75f50 completed download!
> [i] Done!
>

**Comment by 0x776b7364** [comment]
I've pushed out a possible fix. Please test it out and let me know if it still doesn't work.

**Comment by noiseloops** [comment]
yeps, that did the trick. works now for the particular video.
