### ISSUE TITLE
LookUp Error: Unknown Encoding

### ISSUE THREAD

**Issue by cmemil** [0x776b7364/toggle.sg-download#23]
Hi,

Many thanks for your useful utility. I'm having problems downloading any videos. Get a message at the end saying:

LookupError: unknown encoding: cp65001

Is this a system language issue?

**Comment by 0x776b7364** [comment]
Sounds like a Python error message. Do you have a test URL to reproduce the issue?

In another unrelated script, I've had to do the following in the Windows command shell before executing the Python script:
```
c:\> chcp 65001
c:\> set PYTHONIOENCODING=utf-8
```

Try it and see if it fixes the error.

**Comment by cmemil** [comment]
Hi thanks for the suggestion. However I'm still getting the error no matter which video I try. Used your tip on an elevated command prompt.

**Comment by 0x776b7364** [comment]
Are you facing this problem with every video, or only on certain ones? I'm not exactly sure why this occurs, and unfortunately I cannot script that within the Python script (I guess I could wrap it in a batch file...).

**Comment by cmemil** [comment]
Yes, with every video. I remember changing the encoding type manually when I used you-get downloader. A batch file would be nice...thanks.

**Comment by 0x776b7364** [comment]
You can just have something like:
```
@echo off
chcp 65001
set PYTHONIOENCODING=utf-8
echo Calling download_toggle_video2.py %1 ...
download_toggle_video2.py %1
```
You might have to use the ```call``` or ```start``` commands as a prefix to the path where you execute the Python script.

**Comment by cmemil** [comment]
Could you please give me an example for the call or start commands? Haven't used batch commands before.

**Comment by 0x776b7364** [comment]
Sure. It'll either be:
```
call download_toggle_video2.py %1
```
or:
```
start download_toggle_video2.py %1
```

There are differences between them - one will start a new environment (hence disregarding your shell settings of ```chcp``` and ```PYTHONIOENCODING```, and the other will not. Kinda hard for me to try out since I'm not having that issue.

**Comment by cmemil** [comment]
Thanks...I ran the below script but it still throws up the error:

```
@echo off
chcp 65001
set PYTHONIOENCODING=utf-8
start download_toggle_video2.py %1
echo Calling download_toggle_video2.py %1 ...
download_toggle_video2.py %1
```

Replacing the `start` with `call` also yields the same result.

**Comment by 0x776b7364** [comment]
I'd suggest you read up a bit more on batch file programming, and how to call it with parameters (that's what ```%1``` is for) as well as experiment between ```start``` and ```call```..

**Comment by 0x776b7364** [comment]
Issue closed due to a month of no-response. If you're still having issues on this, just re-open this ticket. Thanks!
