### ISSUE TITLE
Unable to download subtitles for whole series.

### ISSUE THREAD

**Issue by qwerty8988** [0x776b7364/toggle.sg-download#24]
Unable to download subtitles if link input is  for whole series.
Example http://tv.toggle.sg/en/channel8/shows/the-dream-makers-2-2-tif/episodes , all 32 videos in the series are able to be downloaded but no subtitles file are downloaded.

If I use individual links from the same series, for example:
http://video.toggle.sg/en/series/the-dream-makers-s2-2/ep1/346548
Both the video and subtitles files are downloaded.

**Comment by 0x776b7364** [comment]
Great find. Pushed a fix in 7d7c5f4. Do give it a shot and see if it works.

**Comment by qwerty8988** [comment]
Hi, it is working perfectly now! Thank you!
