### ISSUE TITLE
line 5 Syntax error

### ISSUE THREAD

**Issue by fahmifong** [0x776b7364/toggle.sg-download#26]
download and install latest python 2.7.11 and ffmpeg-20150418
try on OS windows 7 and 8.1
appear below result for all video, please advice, Thank you.

file "c:\python\download_toggle_video2.py", line 5
  <!DOCTYPE html>
  ^
SyntaxError: Invalid syntax

**Comment by 0x776b7364** [comment]
That's cause you have downloaded the HTML representation of the code from Github. Save the file directly from https://raw.githubusercontent.com/0x776b7364/toggle.sg-download/master/download_toggle_video2.py.

**Comment by fahmifong** [comment]
Thank you. You are the best.
