### ISSUE TITLE
Feature Request - limit output or hide behind --verbose flag

### ISSUE THREAD

**Issue by peterhoeg** [0x776b7364/toggle.sg-download#28]
Currently the script writes a LOT of output concerning internal workings such as 

```
[i] Obtained mediaID = 329066
[i] Performing HTTP GET request on Toggle video URL ...
[i] Obtained apiUser = tvpapi_147
[i] Obtained apiPass = 11111
[i] Performing HTTP GET request on download URL ...
[i] Performing JSON parsing ...
```

That makes sense if you are debugging, but during normal operations, that is just noise. Please hide all that behind a ```---verbose``` or ```--debug``` option so it only shows the actual downloads.

*Edit*: all output is generated by print statements it seems. It makes sense to use one of the logging libraries that automatically gives you logging levels instead.

**Comment by 0x776b7364** [comment]
Great idea, and I very much agree. I'll work on using logging libraries soon.

**Comment by peterhoeg** [comment]
You may also want to apply the ```-loglevel error``` parameter to the ffmpeg command unless debugging.

**Comment by 0x776b7364** [comment]
Pushed 790ff01 and 5d1d351. I've decided to leave the ffmpeg output as it is as I like progress indicators. :)
