### ISSUE TITLE
unable to download toggle movies

### ISSUE THREAD

**Issue by qwerty8988** [0x776b7364/toggle.sg-download#30]
script does not run with this link http://video.toggle.sg/en/movies/unexpected-strangers-free/297421

**Comment by 0x776b7364** [comment]
In future, do indicate more details besides "script does not run". A screenshot, or a dump of the output, or a dump of the debug files, would be nice.
The issue occurred as the available files retrieved somehow included valid file extensions such as m3u8, but does not conform to ```FORMAT_EXPR```.
I've pushed a possible fix 1843bcb.

**Comment by qwerty8988** [comment]
fixed! thanks
