### ISSUE TITLE
Feature Request: convert all options to proper arguments

### ISSUE THREAD

**Issue by peterhoeg** [0x776b7364/toggle.sg-download#31]
A number of options are currently set directly in the script. It would be nice to have the option of setting them as argument to the main script:

``` python
AUTO_DOWNLOAD = 1
CHECK_AND_DOWNLOAD_SUBTITLES = 1
NO_OF_DOWNLOAD_THREADS = 2
```

**Comment by 0x776b7364** [comment]
I'll work on that soon.

**Comment by SwedishGojira** [comment]
It would also be nice to be able to choose to download STB, ADD or IPAD from commandline.
