### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Kerean** [0x776b7364/toggle.sg-download#32]
I seem to be getting an error recently and it affects even old URLs which I managed to download before in the past.  Not too sure if I need to redownload the script (script became corrupt?) or something changed over at Toggle.sg's server end.

This is how the command line looks like before aborting:

=====================================
Toggle video and episodes downloader
by 0x776b7364
=====================================

================================
[*] Processing input 1 of 1 ...
================================

[i] Toggle video http://video.toggle.sg/en/tv-show/news/nov-2016-hello-singapore
/tue-1-nov-2016/456422 detected
[i] Obtained mediaID = 456422
[i] Performing HTTP GET request on Toggle video URL ...
[i] Obtained apiUser = tvpapi_147
[i] Obtained apiPass = 11111
[i] Performing HTTP GET request on download URL ...
[i] Performing JSON parsing ...

[i] Obtaining media name ...
[i] Obtained media name = Nov_2016_-_Hello_Singapore
[i] Obtaining URL records from download URL response ...

Traceback (most recent call last):
  File "C:\Python27\download_toggle_video3.py", line 444, in <module>
    main()
  File "C:\Python27\download_toggle_video3.py", line 422, in main
    records_to_enqueue = process_url(input_url)
  File "C:\Python27\download_toggle_video3.py", line 158, in process_url
    return process_video_url(url)
  File "C:\Python27\download_toggle_video3.py", line 254, in process_video_url
    temp_urlList.append((medianame+"_"+fileformat[0],urlRecord))
IndexError: list index out of range

The command then aborts.

Any idea what happened?

**Comment by gromgit** [comment]
Your command output looks pretty old. You should probably download the latest script and try again.

Here's what the current script output looks like:
```
$ ./download_toggle_video2.py http://video.toggle.sg/en/tv-show/news/nov-2016-hello-singapore/tue-1-nov-2016/456422

=====================================
Toggle video and episodes downloader
by 0x776b7364
=====================================

================================
[*] Processing input 1 of 1 ...
================================
[I] Toggle video http://video.toggle.sg/en/tv-show/news/nov-2016-hello-singapore/tue-1-nov-2016/456422 detected
[I] Obtained media name = Nov_2016_-_Hello_Singapore
[I] Auto-selected URL: http://mcshls2015-vh.akamaihd.net/i/201610WM/MCPK0161101001100500/20161101_NOV_2016_-_HELLO_SINGAPORE_EP1_STB_MP4_,10,30,.mp4.csmil/master.m3u8
[W] No subtitles found!
[I] Starting download of queued URLs ...
[I] Thread adb86dc5: processing URL http://mcshls2015-vh.akamaihd.net/i/201610WM/MCPK0161101001100500/20161101_NOV_2016_-_HELLO_SINGAPORE_EP1_STB_MP4_,10,30,.mp4.csmil/master.m3u8
[...]
```

**Comment by 0x776b7364** [comment]
Closed due to inactivity.
