### ISSUE TITLE
cannot seem to get it working

### ISSUE THREAD

**Issue by punggolzenith** [0x776b7364/toggle.sg-download#33]
strange leh, seems to get the "not a valid url" error code... then sometimes i get this ffmpeg file not found....

**Comment by NGPriest** [comment]
Try copying/moving ffmpeg into the same directory as the script?

**Comment by 0x776b7364** [comment]
Do you mean the error message changes for the same command? That doesn't seem right.. Please indicate the exact command you used, and upload screenshots and the generated debug files if possible.

**Comment by 0x776b7364** [comment]
Closed due to inactivity.
