### ISSUE TITLE
New quality formats and updated gateway urls

### ISSUE THREAD

**Issue by freemanang1989** [0x776b7364/toggle.sg-download#35]
Dear developer, thanks for developing this code, it has served me on many occasions.

Just recently, I realize that the code has issues downloading recent shows. and after a bit of debugging and tracing, I found out that there is a new gateway URL and quality formats. 

I have attached the updated python file, as well as a simple "diff" of the current and edited version by me in a zip file. Improvements are still needed but I have no time on that due to my busy schedule. Hope this updated version helps the community.

[smallUpdate.zip](https://github.com/0x776b7364/toggle.sg-download/files/1017114/smallUpdate.zip)

Cheers

**Comment by 0x776b7364** [comment]
Thanks for the information! I'll work on integrating new options into the script.

**Comment by gaslit** [comment]
many thanks for your hard work on this. :)

**Comment by 0x776b7364** [comment]
So I found out that newer episodes are protected with some DRM which ffmpeg does not have the capacity to download or decrypt at the moment. It is possible that over time, those episodes will have its content restrictions relaxed, but I'm not sure how Mediacorp does it. I'll shortly be pushing a patch which exposes more format selections, but those new format selections are not guaranteed to work.

**Comment by 0x776b7364** [comment]
Pushed af6317a. Let me know what you think. :)

**Comment by NGPriest** [comment]
@0x776b7364 Yep, those are protected for 7 days until after air before the general public can watch it.

If the users want to watch it, i assume a SG VPN/Proxy and a subscription of S$9.90/month is required.

**Comment by 0x776b7364** [comment]
I see; it cannot be helped then. I'll go ahead and close this issue (strictly speaking; this is not an issue), and thanks to all who participated and to @freemanang1989 for the improvements. New issues may be raised if there are any problems with the new exposed format selections.
