### ISSUE TITLE
New Problem Downloading Toggle Episodes

### ISSUE THREAD

**Issue by Kerean** [0x776b7364/toggle.sg-download#37]
Not sure if it is a problem with the script or a problem with the way Toggle now serves videos, but for a couple of days I've not been able to download.

One example is 

https://video.toggle.sg/en/series/118-s2/ep129/513405

Tried setting AUTO_DOWNLOAD to 0 but also no joy.  Hope you can help!

[I] Toggle video https://video.toggle.sg/en/series/118-s2/ep129/513405 detected
[I] Obtained media name = 118_S2_-_Episode_129
[E] No files selected based on FILE_PREFERENCES
[E] Consider relaxing preference criteria, or setting AUTO_DOWNLOAD to 0
[I] Found English subtitles! Adding to queue list ...
[I] Found Chinese subtitles! Adding to queue list ...
[I] Starting download of queued URLs ...
[I] Thread f531df64: processing URL https://cc-toggle.akamaized.net/513405_DAQ14
979_CE.SRT
[I] Thread 34a82759: processing URL https://cc-toggle.akamaized.net/513405_DAQ14
979_CC.SRT
[I] Thread f531df64 completed
[I] Thread 34a82759 completed
[I] === Script execution complete! ===

**Comment by 0x776b7364** [comment]
Did you use the latest version of the script? Try running it again, with debug mode ```-d``` enabled, and paste the output here. Also, please indicate if the episode has been released recently.

**Comment by Kerean** [comment]
Thanks for the quick reply, I didn't realise there was a new version as of May.  Just downloaded and so far it seems to work, will feedback again if I encounter problems.

**Comment by 0x776b7364** [comment]
Glad it works for you. :)
