### ISSUE TITLE
Download foreign shows (DRM-protected?)

### ISSUE THREAD

**Issue by ds2003** [0x776b7364/toggle.sg-download#38]
Hi

I'm not technically savvy so I'm not sure if this had been mentioned or discussed before.

Is there any way to download those foreign shows from China or USA or UK?

I would love to download the following series + the latest Earth 2 series from BBC but the script returns 

[hls,applehttp @ 00000000006328e0] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 00000000006328e0] Failed to open segment of playlist 0

These are 2 urls from the shows:
https://video.toggle.sg/en/series/my-amazing-bride/ep37/515093
https://video.toggle.sg/en/series/planet-earth-ii/ep1/519847

Regards

DS

**Comment by 0x776b7364** [comment]
Foreign shows are usually encrypted with some DRM and are thus not directly playable with conventional players like VLC.

**Comment by 0x776b7364** [comment]
Closed due to inactivity.
