### ISSUE TITLE
Unable to download anything? 

### ISSUE THREAD

**Issue by MintyMints** [0x776b7364/toggle.sg-download#40]
Hi, I kinda received the following error using windows command, 
was able to download before, but I was unable to download anything today. Do you have a solution for this issue? Thank you.

C:\Python27>download_toggle_video2.py https://video.toggle.sg/en/series/josiah-hd/ep8/518734

[I] Toggle video https://video.toggle.sg/en/series/josiah-hd/ep8/518734 detected
[W] Unable to obtain api user / password
[W] Nothing to download for https://video.toggle.sg/en/series/josiah-hd/ep8/518734
[E] No files in queue
[I] Quitting ...
[I] === Script execution complete! ===

**Comment by gromgit** [comment]
I don't use Windows, but the download works just fine on Linux:
```
$ toggle.sg https://video.toggle.sg/en/series/josiah-hd/ep8/518734

=====================================
Toggle video and episodes downloader
by 0x776b7364
=====================================

================================
[*] Processing input 1 of 1 ...
================================
[I] Toggle video https://video.toggle.sg/en/series/josiah-hd/ep8/518734 detected
[I] Obtained media name = Josiah__HD__-_Episode_8
[I] Auto-selected URL: http://cdnapi.kaltura.com/p/2082311/sp/208231100/playManifest/protocol/http/entryId/0_to176qmq/format/applehttp/tags/hlstv_hd/f/a.m3u8
[I] Found English subtitles! Adding to queue list ...
[I] Starting download of queued URLs ...
[I] Thread f5e0bb74: processing URL http://cdnapi.kaltura.com/p/2082311/sp/208231100/playManifest/protocol/http/entryId/0_to176qmq/format/applehttp/tags/hlstv_hd/f/a.m3u8
[I] Thread 3a397e3c: processing URL https://cc-toggle.akamaized.net/518734_DAJ15716_English.srt
Downloading: 518734_DAJ15716_English.srt Bytes: 22420
...
```
The toggle.sg script was last updated May 26. If you haven't updated since then, download the latest version and try again.

**Comment by MintyMints** [comment]
@gromgit seems to be working now for the newer shows. But then for the older shows for example, this one;  I received an error like this. Is there a solution for it? Thank you. 

[I] Thread 5366e283 completed
[http @ 0000000000196d80] HTTP error 404 Not Found
http://mcshls-vh.akamaihd.net/i/201509I/MCPK1109160214530853/MC_HD_BREAKOUT_EP25_STB_MP4_,10,20,30,40,.mp4.csmil/master.m3u8: Server returned 404 Not Found
[E] ffmpeg file not found, or existing file is for incorrect architecture, or download was interrupted prematurely.
[I] Thread 39a848aa completed
[I] === Script execution complete! ===

**Comment by gromgit** [comment]
@MintyMints Assuming the session was for Breakout Ep 25 (i.e. https://video.toggle.sg/en/series/breakout/ep25/203658), I can't even play the video from my browser. If you can't do that either, it's a good bet that the problem is on Toggle's backend.

**Comment by MintyMints** [comment]
@gromgit That's strange, because I am able to stream it on my browser, just that I am unable to download the file. Actually not only for this series but this problem also occurs for the other older shows.
I tried the other download format, but it seems that the error only occurs when selecting STB (which is the best quality for the older shows).

**Comment by 0x776b7364** [comment]
@MintyMints are you still facing this issue? FWIW, I can stream the Breakout Ep 25 video on Safari while in SG. I can take a closer look if the issue is still occurring.

**Comment by MintyMints** [comment]
@0x776b7364  Hi, yes I'm still facing this issue, actually not only for this particular episode but for most of the older series. It's like whenever I am selecting STB quality, there will be error popping out; 

[I] Thread 70a19488 completed
[http @ 0000000000196d80] HTTP error 404 Not Found
http://mcshls-vh.akamaihd.net/i/201509I/MCPK1109160214530853/MC_HD_BREAKOUT_EP25_STB_MP4_,10,20,30,40,.mp4.csmil/master.m3u8: Server returned 404 Not Found
[E] ffmpeg file not found, or existing file is for incorrect architecture, or download was interrupted prematurely.
[I] Thread 7aa4d30f completed
[I] === Script execution complete! ===

**Comment by 0x776b7364** [comment]
It would seem that the STB links aren't working. Have you tried the other formats? Specifically, the following seems to work well:
- mobile_hd: getting 540p mp4
- web_hd: getting 720p mp4

**Comment by MintyMints** [comment]
@0x776b7364 Yeap, have tried the other formats, they are working but the graphic quality isn't as good as STB.

**Comment by 0x776b7364** [comment]
Unfortunately I can't do anything if STB is not available. The retrieved quality list and the corresponding URLs are correct though. Perhaps you'll have to monitor the site to see when that version is uploaded.

**Comment by 0x776b7364** [comment]
Closed due to inactivity.
