### ISSUE TITLE
Trouble downloading older videos

### ISSUE THREAD

**Issue by SwedishGojira** [0x776b7364/toggle.sg-download#44]
Episode 1 (https://video.toggle.sg/en/series/crimewatch-2017/ep1/484145) and 2 (https://video.toggle.sg/en/series/crimewatch-2017/ep2/488673)  will not download, but newer episodes will. (http://tv.toggle.sg/en/channel5/shows/crimewatch-2017-tif/episodes)

**Comment by 0x776b7364** [comment]
Updated version works well for your stated episodes. Test it out and let me know?

**Comment by SwedishGojira** [comment]
Working nicely now :) Thanks!
