### ISSUE TITLE
[E] ffmpeg file not found, or existing file is for incorrect architecture, or do wnload was interrupted prematurely.

### ISSUE THREAD

**Issue by Kerean** [0x776b7364/toggle.sg-download#48]
Having errors downloading this: https://video.toggle.sg/en/series/genius-go-go-go-2018-lny-special/ep1/567705

[hls,applehttp @ 038c3600] Failed to open segment of playlist 0
[hls,applehttp @ 038c3600] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 038c3600] Failed to open segment of playlist 0
[hls,applehttp @ 038c3600] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 038c3600] Failed to open segment of playlist 0
[hls,applehttp @ 038c3600] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 038c3600] Failed to open segment of playlist 0
[hls,applehttp @ 038c3600] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 038c3600] Failed to open segment of playlist 0
[hls,applehttp @ 038c3600] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 038c3600] Failed to open segment of playlist 0
[hls,applehttp @ 038c3600] Error when loading first segment 'http://k.toggle.sg/
fpshls/p/2082311/sp/208231100/serveFlavor/entryId/0_mvqb731a/v/2/pv/1/ev/17/flav
orId/0_k68uj0sk/name/a.mp4/seg-1-v1-a1.ts'
http://cdnapi.kaltura.com/p/2082311/sp/208231100/playManifest/protocol/http/entr
yId/0_mvqb731a/format/applehttp/tags/hlstv_hd/f/a.m3u8: Invalid data found when
processing input
[E] ffmpeg file not found, or existing file is for incorrect architecture, or do
wnload was interrupted prematurely.
[I] Thread 0569c503 completed
[I] === Script execution complete! ===

**Comment by 0x776b7364** [comment]
Are you still facing this issue? The toggle link you've provided is invalid though.

**Comment by faithcsc** [comment]
It's here https://tv.toggle.sg/en/shows/genius-go-go-go-2018-lny-speci-1/episodes but premium so that may be the issue

**Comment by 0x776b7364** [comment]
Closed due to inactivity. Please reopen the issue if you're still facing this problem.
