### ISSUE TITLE
"SAMPLE-AES encryption is not supported yet" with newly added shows

### ISSUE THREAD

**Issue by faithcsc** [0x776b7364/toggle.sg-download#50]
Tried to download https://video.toggle.sg/en/series/trendsetters/ep1/569861

Autodownload was turned off. Script detected and attempted to download five files:

```
[1]: Trendsetters_-_Episode_1_mobile_hd
[2]: Trendsetters_-_Episode_1_web_hd
[3]: Trendsetters_-_Episode_1_hlstv_hd
[4]: Trendsetters_-_Episode_1_tablet_hd
[5]: Trendsetters_-_Episode_1_tablet_hd
```

all of the files produced something similar to this error:

```
[hls,applehttp @ 0000000005769bc0] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 0000000005769bc0] Failed to open segment of playlist 0
[hls,applehttp @ 0000000005769bc0] SAMPLE-AES encryption is not supported yet
[hls,applehttp @ 0000000005769bc0] Failed to open segment of playlist 0
[hls,applehttp @ 0000000005769bc0] Error when loading first segment 'http://k.toggle.sg/fpshls/p/2082311/sp/208231100/serveFlavor/entryId/0_xqx58cfw/v/2/pv/1/ev/17/flavorId/0_nh8cup1x/name/a.mp4/seg-1-v1-a1.ts'
http://cdnapi.kaltura.com/p/2082311/sp/208231100/playManifest/protocol/http/entryId/0_xqx58cfw/format/applehttp/tags/tablet_hd/f/a.m3u8: Invalid data found when processing input
[E] ffmpeg file not found, or existing file is for incorrect architecture, or download was interrupted prematurely.
[I] Thread 44d0118b completed
[I] +++ Script execution complete! +++
```

Seems to be an issue only with newly-added tv shows:

- Older shows (https://video.toggle.sg/en/series/my-friends-from-afar/ep25/557131) can still be downloaded
- Newer episodes of not-recently-added-shows (https://video.toggle.sg/en/series/tanglin/ep684/571329) can still be downloaded
- Newly added shows (https://video.toggle.sg/en/series/trendsetters/ep1/569861) produce this error.

**Comment by 0x776b7364** [comment]
This seems to be a commonly-reported issue; try downloading the episode again in a few days (at least a week) and see if you encounter the same problems.

**Comment by 0x776b7364** [comment]
I've just tried, and it seems like the episode download is working well for your link.

**Comment by faithcsc** [comment]
oh it does work now! thanks for your help.
