### ISSUE TITLE
Unable to find suitable output format

### ISSUE THREAD

**Issue by zedabyu** [0x776b7364/toggle.sg-download#51]
+++++++++++++++++++++++++++++++++++++
Toggle video and episodes downloader
+++++++++++++++++++++++++++++++++++++

+++++++++++++++++++++++++++++++++++++
[*] Processing input 1 of 1 ...
+++++++++++++++++++++++++++++++++++++
[I] Toggle video https://video.toggle.sg/en/series/phua-chu-kang-pte-ltd-s1/ep18
/257478 detected
[I] Obtained media name = Phua_Chu_Kang_Pte_Ltd_S1_-_Episode_18
[I] Auto-selected URL: http://cdnapi.kaltura.com/p/2082311/sp/208231100/playMani
fest/protocol/http/entryId/0_q7ik9ifm/format/applehttp/tags/hlstv_sd/f/a.m3u8
[W] No subtitles found!
[I] Starting download of queued URLs ...
[I] Thread 1efc8594: processing URL http://cdnapi.kaltura.com/p/2082311/sp/20823
1100/playManifest/protocol/http/entryId/0_q7ik9ifm/format/applehttp/tags/hlstv_s
d/f/a.m3u8
ffmpeg version N-90315-gf706cdda56 Copyright (c) 2000-2018 the FFmpeg developers

  built with gcc 7.3.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --e
nable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libblur
ay --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-
libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enab
le-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-li
bvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --en
able-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-
libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enabl
e-libspeex --enable-libxvid --enable-libmfx --enable-amf --enable-ffnvcodec --en
able-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enabl
e-avisynth
  libavutil      56.  9.100 / 56.  9.100
  libavcodec     58. 14.100 / 58. 14.100
  libavformat    58. 10.100 / 58. 10.100
  libavdevice    58.  2.100 / 58.  2.100
  libavfilter     7. 13.100 /  7. 13.100
  libswscale      5.  0.102 /  5.  0.102
  libswresample   3.  0.101 /  3.  0.101
  libpostproc    55.  0.100 / 55.  0.100
[NULL @ 0000000000691080] Unable to find a suitable output format for 'http://vi
deo.toggle.sg/'
http://video.toggle.sg/: Invalid argument
[E] ffmpeg file not found, or existing file is for incorrect architecture, or do
wnload was interrupted prematurely.
[I] Thread 1efc8594 completed
[I] +++ Script execution complete! +++

**Comment by 0x776b7364** [comment]
Closed due to inactivity.
