### ISSUE TITLE
Line 460 doesn't work in Windows

### ISSUE THREAD

**Issue by win98se** [0x776b7364/toggle.sg-download#52]
Windows doesn't support `os.uname()`, so the line 460 (`logger.debug(os.uname())`) causes an error in Windows. I commented that line and everything else works as expected.

**Comment by 0x776b7364** [comment]
I'm not supporting Windows anymore; in any case, I believe `platform.uname()` should do the trick. Perhaps submit a PR? :)

**Comment by 0x776b7364** [comment]
@win98se Possible fix pushed as b930d1f

**Comment by win98se** [comment]
@0x776b7364 Thank you, solved.

@NGPriest There aren't any issues here with line 73 using `http?` instead of `https`.
