### ISSUE TITLE
WVM are encrypted with Webvine DRM

### ISSUE THREAD

**Issue by CKtalon** [0x776b7364/toggle.sg-download#6]
The WVM files downloaded are encrypted with Webvine DRM, which effectively renders this moot.

**Comment by gromgit** [comment]
It seems to be an issue only for US-produced shows. Most local and some BBC-produced shows are DRM-free, and seem to be handled perfectly fine.

In any event, the logical place to fix this is in ffmpeg, but it's had an [open Widevine support ticket](https://trac.ffmpeg.org/ticket/1793), for 3 *years*, so it's probably not happening any time soon. That said, the download script seems to pull down the original bytes just fine, so if there are any shows you really want to <cough>*archive*</cough>, you can still pull the WVMs down first, then wait for ffmpeg or another encoder or standalone player to "support" Widevine.

**Comment by 0x776b7364** [comment]
Oops, forgot to close the issue; yes, great explanation by @gromgit, thanks for that.
