### ISSUE TITLE
Website change, request for new source code

### ISSUE THREAD

**Issue by ChinHuiHing** [0x776b7364/toggle.sg-download#61]
Hi, the toggle.sg website will change to mewatch starting from 30 January 2020, after the website changed most probably the existing source code cannot be use. Will you modify the code for the new website?

**Comment by 0x776b7364** [comment]
The existing code will not be modified to accommodate the name change to 'rewatch'. In fact, this project may be archived after Jan 30 2020 since I won't be making changes anymore.
